name: chat_app_pro
description: A modern Flutter chat app.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- FIREBASE ---
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  # firebase_storage: ^12.1.0  <-- NONAKTIFKAN KARENA PAKAI IMGBB
  
  # --- UI & TOOLS ---
  google_fonts: ^6.1.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  any_link_preview: ^3.0.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  http: ^1.2.1               # WAJIB UNTUK IMGBB
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.0    # UNTUK ANIMASI UI

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/