name: chat_app_keren_baru_banget
description: A modern Flutter chat app with real-time messaging.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- PAKET WAJIB GENERASI 3 ---
  any_link_preview: ^3.0.0  # Buat preview link ala WhatsApp
  # ----------------------------
  
  http: ^1.2.1
  cached_network_image: ^3.3.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.1.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  flutter_vector_icons: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/